steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/aicoexist-446217/aisense-repo/rice_monitor_api'
      - '.'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/aicoexist-446217/aisense-repo/rice_monitor_api'

  # ✅ Step 3: Deploy to Cloud Run with secure configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    dir: 'backend'
    args:
      - '-c'
      - |
        echo "🚀 Deploying to Cloud Run..."
        gcloud run deploy rice-monitor-api \
          --image=us-central1-docker.pkg.dev/aicoexist-446217/aisense-repo/rice_monitor_api \
          --platform=managed \
          --region=us-central1 \
          --port=8989 \
          --service-account=rice-field-monitor@aicoexist-446217.iam.gserviceaccount.com \
          --project=aicoexist-446217 \
          --allow-unauthenticated \
          --timeout=500s \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=aicoexist-446217,STORAGE_BUCKET=rice_storage,GIN_MODE=release,ENVIRONMENT=production" \
          --update-secrets=GOOGLE_CLIENT_ID=google-client-id:latest,JWT_SECRET=jwt-secret:latest,GOOGLE_API_KEY=google-api-key:latest,/etc/secrets/firebase-admin-service-account.json=firebase-admin-credentials:latest

images:
  - 'us-central1-docker.pkg.dev/aicoexist-446217/aisense-repo/rice_monitor_api'

options:
  logging: CLOUD_LOGGING_ONLY
